apiVersion: v1
kind: ConfigMap
metadata:
  name: transport-telemetry-config
data:
    telemetry.tracingEndpoint: "http://jaeger-collector.istio-system:14268/api/traces"
    telemetry.loggingEndpoint: "http://seq.default:5341/"
    telemetry.name: transport.default
    telemetry.version: "{{ .Chart.Version }}"