apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
    name: transport
spec:
    host: transport
    subsets:
      - name: amazing-transport
        labels:
          version: amazing-transport
      - name: trashy-transport
        labels:
          version: trashy-transport