apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration
  labels:
    app: registration
    version: {{ .Chart.Version }}
spec:
  selector:
    matchLabels:
      app: registration
      version: {{ .Chart.Version }}
  template:
    metadata:
      labels:
        app: registration
        version: {{ .Chart.Version }}
      annotations:
        dapr.io/app-id: "registration"
        dapr.io/app-port: "80"
        dapr.io/enabled: "true"
        sidecar.opentelemetry.io/inject: "true"
        prometheus.io/port: "80"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: registration
      containers:
        - name: registration
          image: "{{ .Values.global.containerRegistry }}/registration:{{ .Values.global.releaseVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: TELEMETRY__LOGGINGENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: customermanagement-config
                  key: "telemetry.loggingEndpoint"
            - name: TELEMETRY__TRACINGENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: customermanagement-config
                  key: "telemetry.tracingEndpoint"
            - name: TELEMETRY__NAME
              valueFrom:
                configMapKeyRef:
                  name: registration-config
                  key: "telemetry.name"
            - name: TELEMETRY__VERSION
              valueFrom:
                configMapKeyRef:
                  name: registration-config
                  key: "telemetry.version"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
