apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration
  labels:
    app: registration
    version: {{ .Chart.Version }}
spec:
  selector:
    matchLabels:
      app: registration
      version: {{ .Chart.Version }}
  template:
    metadata:
      labels:
        app: registration
        version: {{ .Chart.Version }}
      annotations:
        dapr.io/app-id: "registration"
        dapr.io/app-port: "80"
        dapr.io/enabled: "true"
        sidecar.opentelemetry.io/inject: "true"
    spec:
      serviceAccountName: registration
      containers:
        - name: registration
          image: recommendcoffee.azurecr.io/registration:{{ .Values.global.releaseVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: IMAGE_TAG
              value: "{{ .Chart.Version }}"
            - name: OTLP__ENDPOINT
              value: "http://localhost:4317"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
