apiVersion: v1
kind: Service
metadata:
  name: registration
  labels:
    app: registration
    version: {{ .Chart.Version }}
spec:
  selector:
    app: registration
    version: {{ .Chart.Version }}
  ports:
  - port: 80
    targetPort: 80
