apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: registration-virtual-service
spec:
  hosts:
  - "recommend.coffee"
  gateways:
  - recommendcoffee-gateway
  http:
  - name: registration-route
    match:
      - uri:
          prefix: /registration/
    rewrite:
      uri: /
    route:
    - destination:
        host: registration.default.svc.cluster.local
        port:
          number: 80