apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    app: shipping
    service: shipping
    version: v1
spec:
  type: ClusterIP
  selector:
    app: shipping
    service: shipping
    version: v1
  ports:
  - port: 80
    name: http
