apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    app: shipping
    version: {{ .Chart.Version }}
spec:
  type: ClusterIP
  selector:
    app: shipping
    version: {{ .Chart.Version }}
  ports:
  - port: 80
    name: http
