apiVersion: v2
name: recommend-coffee
description: A Helm chart for the Recommend-Coffee sample solution
type: application
version: 0.1.0-alpha.1
appVersion: 1.16.0
dependencies:
  - name: shared
    version: 0.1.0-alpha.1
  - name: database
    version: 0.1.0-alpha.1
  - name: redis
    version: 0.1.0-alpha.1
  - name: rabbitmq
    version: 0.1.0-alpha.1
  - name: zipkin
    version: 0.1.0-alpha.1
  - name: prometheus
    version: 0.1.0-alpha.1
  - name: catalog
    version: 0.1.0-alpha.1
  - name: otel-collector
    version: 0.1.0-alpha.1
  - name: customermanagement
    version: 0.1.0-alpha.1
  - name: payments
    version: 0.1.0-alpha.1
  - name: ratings
    version: 0.1.0-alpha.1
  - name: registration
    version: 0.1.0-alpha.1
  - name: subscriptions
    version: 0.1.0-alpha.1