apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  labels:
    app: payments
    version: {{ .Chart.Version }}
spec:
  selector:
    matchLabels:
      app: payments
      version: {{ .Chart.Version }}
  template:
    metadata:
      labels:
        app: payments
        version: {{ .Chart.Version }}
      annotations:
        dapr.io/app-id: "payments"
        dapr.io/app-port: "80"
        dapr.io/enabled: "true"
        sidecar.opentelemetry.io/inject: "true"
        prometheus.io/port: "80"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: payments
      containers:
        - name: payments
          image: recommendcoffee.azurecr.io/payments:{{ .Values.global.releaseVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: CONNECTIONSTRINGS__DEFAULTDATABASE
              valueFrom:
                secretKeyRef:
                  key: paymentsConnectionString
                  name: recommend-coffee-secrets
            - name: IMAGE_TAG
              value: "{{ .Chart.Version }}"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TELEMETRY__SPANS
              value: "http://jaeger-collector.istio-system:14268/api/traces"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
      initContainers:
        - name: database-migrations
          image: recommendcoffee.azurecr.io/payments-migrations:{{ .Values.global.releaseVersion }}
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: recommend-coffee-secrets
                  key: databasePassword
            - name: DB_USER
              value: sa
            - name: DB_NAME
              value: payments
            - name: DB_SERVER
              value: database
