apiVersion: v1
kind: Service
metadata:
  name: payments
  labels:
    app: customermanagement
    version: {{ .Chart.Version }}
spec:
  selector:
    app: payments
    version: {{ .Chart.Version }}
  ports:
  - port: 80
    name: http
