apiVersion: v1
kind: Service
metadata:
  name: payments
  labels:
    app: payments
    service: payments
    version: v1
spec:
  selector:
    app: payments
    service: payments
    version: v1
  ports:
  - port: 80
    name: http
