apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
      annotations:
        dapr.io/app-id: "gateway"
        dapr.io/config: "recommendcoffee-dapr-config"
        dapr.io/app-port: "80"
        dapr.io/enabled: "true"
    spec:
      containers:
        - name: gateway
          image: envoyproxy/envoy:v1.21.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy/envoy.yaml
              subPath: envoy.yaml
      volumes:
        - name: envoy-config
          configMap:
            name: recommendcoffee-envoy-config
            items:
              - key: envoy.yaml
                path: envoy.yaml