apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriptions
spec:
  selector:
    matchLabels:
      app: subscriptions
  template:
    metadata:
      labels:
        app: subscriptions
    spec:
      containers:
      - name: subscriptions
        image: recommendcoffee/subscriptions:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
