apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriptions
  annotations:
    dapr.io/app-id: subscriptions
    dapr.io/config: recommend-coffee-config
    dapr.io/app-port: "80"
    dapr.io/enabled: "true"
spec:
  selector:
    matchLabels:
      app: subscriptions
  template:
    metadata:
      labels:
        app: subscriptions
    spec:
      containers:
      - name: subscriptions
        image: recommendcoffee.azurecr.io/subscriptions:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: CONNECTIONSTRINGS__DEFAULTDATABASE
            valueFrom:
              secretKeyRef:
                key: subscriptionsConnectionString
                name: recommend-coffee-secrets
