apiVersion: v1
kind: Service
metadata:
  name: recommendations
  labels:
    app: recommendations
    service: recommendations
spec:
  type: ClusterIP
  selector:
    app: recommendations
    service: recommendations
  ports:
  - port: 80
    name: http
