version: "3.9"
services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - 1433:1433
  catalog:
    image: recommendcoffee/catalog
    build: 
      context: services/catalog
      dockerfile: Dockerfile
    ports:
      - 5000:80
    environment:
      CONNECTIONSTRINGS__DEFAULTDATABASE: "data source=database;initial catalog=catalog;user id=sa;password=${DB_PASSWORD};MultipleActiveResultSets=True"
  catalog-dapr:
    image: daprio/daprd:1.6.0
    command: ["./daprd", "-app-id", "catalog", "-app-port", "80","-components-path","/dapr/components", "-config","/configuration/config.yaml"]
    volumes:
      - ./dapr/configuration:/configuration
      - ./dapr/components:/dapr/components
  customermanagement:
    image: recommendcoffee/customermanagement
    build: 
      context: services/customers
      dockerfile: Dockerfile
    ports:
      - 5001:80
    environment:
      CONNECTIONSTRINGS__DEFAULTDATABASE: "data source=database;initial catalog=customers;user id=sa;password=${DB_PASSWORD};MultipleActiveResultSets=True"
  customermanagement-dapr:
    image: daprio/daprd:1.6.0
    command: ["./daprd", "-app-id", "customermanagement", "-app-port", "80","-components-path","/dapr/components", "-config","/configuration/config.yaml"]
    network_mode: service:customermanagement
    volumes:
      - ./dapr/configuration:/configuration
      - ./dapr/components:/dapr/components
    depends_on:
      - customermanagement
      - kafka
      - redis
  subscriptions:
    image: recommendcoffee/subscriptions
    build: 
      context: services/subscriptions
      dockerfile: Dockerfile
    ports:
      - 5002:80
    environment:
      CONNECTIONSTRINGS__DEFAULTDATABASE: "data source=database;initial catalog=subscriptions;user id=sa;password=${DB_PASSWORD};MultipleActiveResultSets=True"
  subscriptions-dapr:
    image: daprio/daprd:1.6.0
    command: ["./daprd", "-app-id", "subscriptions", "-app-port", "80","-components-path","/dapr/components", "-config","/configuration/config.yaml"]
    network_mode: service:subscriptions
    volumes:
      - ./dapr/configuration:/configuration
      - ./dapr/components:/dapr/components
    depends_on:
      - subscriptions
      - kafka
      - redis
  registration:
    image: recommendcoffee/registration
    build: 
      context: services/registration
      dockerfile: Dockerfile
    ports:
      - 5003:80
  registration-dapr:
    image: daprio/daprd:1.6.0
    command: ["./daprd", "-app-id", "registration", "-app-port", "80","-components-path","/dapr/components", "-config","/configuration/config.yaml"]
    network_mode: service:registration
    volumes:
      - ./dapr/configuration:/configuration
      - ./dapr/components:/dapr/components
    depends_on:
      - registration
      - kafka
      - redis
  zipkin: 
    image: openzipkin/zipkin
    ports:
     - 9411:9411
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:5.0.0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  redis:
    image: redis:6.2.6
    environment:
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
