apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
    name: grafana
    namespace: default
spec:
    selector:
        matchLabels:
            app: grafana
    mtls:
        mode: DISABLE
