apiVersion: apps/v1
kind: Deployment
metadata:
  name: timer
  labels:
    app: timer
    version: {{ .Chart.Version }}
spec:
  selector:
    matchLabels:
      app: timer
      version: {{ .Chart.Version }}
  template:
    metadata:
      labels:
        app: timer
        version: {{ .Chart.Version }}
      annotations:
        dapr.io/app-id: "timer"
        dapr.io/app-port: "80"
        dapr.io/enabled: "true"
        sidecar.opentelemetry.io/inject: "true"
        prometheus.io/port: "80"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: timer
      containers:
        - name: timer
          image: recommendcoffee.azurecr.io/timer:{{ .Values.global.releaseVersion }}
          imagePullPolicy: IfNotPresent
          env:
            - name: TIMERS__MONTHHASPASSED
              value: "30 * * * * *"
            - name: TELEMETRY__ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: timer-config
                  key: "telemetry.endpoint"
            - name: TELEMETRY__NAME
              valueFrom:
                configMapKeyRef:
                  name: timer-config
                  key: "telemetry.name"
            - name: TELEMETRY__VERSION
              valueFrom:
                configMapKeyRef:
                  name: timer-config
                  key: "telemetry.version"
          ports:
            - containerPort: 80
              name: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
