apiVersion: apps/v1
kind: Deployment
metadata:
  name: timer
  labels:
    app: timer
    version: {{ .Chart.Version }}
spec:
  selector:
    matchLabels:
      app: timer
      version: {{ .Chart.Version }}
  template:
    metadata:
      labels:
        app: timer
        version: {{ .Chart.Version }}
      annotations:
        dapr.io/app-id: "timer"
        dapr.io/app-port: "80"
        dapr.io/enabled: "true"
        sidecar.opentelemetry.io/inject: "true"
        prometheus.io/port: "80"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: timer
      containers:
        - name: timer
          image: recommendcoffee.azurecr.io/timer:{{ .Values.global.releaseVersion }}
          imagePullPolicy: IfNotPresent
          env:
            - name: TIMERS__MONTHHASPASSED
              value: "30 * * * * *"
            - name: IMAGE_TAG
              value: "{{ .Chart.Version }}"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TELEMETRY__SPANS
              value: "http://jaeger-collector.istio-system:14268/api/traces"
          ports:
            - containerPort: 80
              name: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
