apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
    name: database
    namespace: default
spec:
    selector:
        matchLabels:
            app: database
    mtls:
        mode: DISABLE
