apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  labels:
    app: catalog
    version: {{ .Chart.Version }}
spec:
  selector:
    matchLabels:
      app: catalog
      version: {{ .Chart.Version }}
  template:
    metadata:
      labels:
        app: catalog
        version: {{ .Chart.Version }}
      annotations:
        dapr.io/app-id: "catalog"
        dapr.io/config: "recommendcoffee-dapr-config"
        dapr.io/app-port: "80"
        dapr.io/enabled: "true"
    spec:
      serviceAccountName: catalog
      containers:
        - name: catalog
          image: recommendcoffee.azurecr.io/catalog:{{ .Values.global.releaseVersion }}
          imagePullPolicy: IfNotPresent
          env:
            - name: CONNECTIONSTRINGS__DEFAULTDATABASE
              valueFrom:
                secretKeyRef:
                  name: recommend-coffee-secrets
                  key: catalogConnectionString
            - name: IMAGE_TAG
              value: "{{ .Chart.Version }}"
            - name: OTLP__ENDPOINT
              value: "http://otel-collector:4317"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
      initContainers:
        - name: database-migrations
          image: recommendcoffee.azurecr.io/catalog-migrations:{{ .Values.global.releaseVersion }}
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: recommend-coffee-secrets
                  key: databasePassword
            - name: DB_USER
              value: sa
            - name: DB_NAME
              value: catalog
            - name: DB_SERVER
              value: database
