apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  annotations:
    dapr.io/app-id: ratings
    dapr.io/config: recommend-coffee-config
    dapr.io/app-port: "80"
    dapr.io/enabled: "true"
spec:
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      containers:
      - name: ratings
        image: recommendcoffee.azurecr.io/ratings
        imagePullPolicy: IfNotPresent
        env:
          - name: CONNECTIONSTRINGS__DEFAULTDATABASE
            valueFrom:
              secretKeyRef:
                name: recommend-coffee-secrets
                key: ratingsConnectionString
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80