apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    service: rabbitmq
spec:
  selector:
    app: rabbitmq
    service: rabbitmq
  ports:
  - port: 5672
    targetPort: 5672
    name: tcp-amqp
  - port: 15672
    targetPort: 15672
    name: http