apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration
spec:
  selector:
    matchLabels:
      app: registration
  template:
    metadata:
      labels:
        app: registration
    spec:
      containers:
      - name: registration
        image: recommendcoffee.azurecr.io/registration
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: CONNECTIONSTRINGS__DEFAULTDATABASE
            valueFrom:
              secretKeyRef:
                key: registrationConnectionString
                name: recommend-coffee-secrets
