apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
    service: database
    version: v1
spec:
  selector:
    matchLabels:
      app: database
      service: database
      version: v1
  template:
    metadata:
      labels:
        app: database
        service: database
        version: v1
    spec:
      serviceAccountName: database
      volumes:
      - name: database-volume
        persistentVolumeClaim:
          claimName: database-volume-claim
      containers:
      - name: database
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
          name: tcp-sql
        env:
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                key: databasePassword
                name: recommend-coffee-secrets
          - name: ACCEPT_EULA
            value: "Y"
        volumeMounts:
          - name: database-volume
            mountPath: /var/opt/mssql