apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
    name: database
spec:
    hosts:
    - database
    ports:
    - number: 1433
      name: sqlserver
      protocol: TCP
    resolution: DNS
    location: MESH_EXTERNAL