apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailserver
  labels:
    app: emailserver
    service: emailserver
    version: v1
spec:
  selector:
    matchLabels:
      app: emailserver
      service: emailserver
      version: v1
  template:
    metadata:
      labels:
        app: emailserver
        service: emailserver
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: emailserver
      containers:
      - name: emailserver
        image: maildev/maildev
        ports:
        - containerPort: 1080
          name: http
        - containerPort: 1025
          name: smtp
