apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailserver
spec:
  selector:
    matchLabels:
      app: emailserver
  template:
    metadata:
      labels:
        app: emailserver
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: emailserver
        image: maildev/maildev
        ports:
        - containerPort: 1080
          name: http
        - containerPort: 1025
          name: smtp
