apiVersion: v1
kind: Service
metadata:
  name: emailserver
  labels:
    app: emailserver
    service: emailserver
spec:
  selector:
    app: emailserver
    service: emailserver
  ports:
  - port: 25
    targetPort: 1025
    name: smtp
    appProtocol: tcp
  - port: 1080
    targetPort: 1080
    name: http
