apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: emailserver
spec:
    hosts:
    - emailserver
    http:
    - route:
      - destination:
          host: emailserver
          subset: v1
