apiVersion: v1
kind: Service
metadata:
  name: recommendations
  labels:
    app: recommendations
    service: recommendations
    version: v1
spec:
  type: ClusterIP
  selector:
    app: recommendations
    version: {{ .Chart.Version }}
  ports:
  - port: 80
    name: http
