apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    service: redis
    version: v1
spec:
  selector:
    matchLabels:
      app: redis
      service: redis
      version: v1
  template:
    metadata:
      labels:
        app: redis
        service: redis
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: redis
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
          name: redis
        livenessProbe:
          tcpSocket:
            port: redis
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
