apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
    name: redis
spec:
    hosts:
    - redis
    ports:
    - number: 6379
      name: redis
      protocol: TCP
    resolution: DNS
    location: MESH_EXTERNAL