apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  annotations:
    dapr.io/app-id: catalog
    dapr.io/config: recommend-coffee-config
    dapr.io/app-port: "80"
    dapr.io/enabled: "true"
spec:
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: recommendcoffee.azurecr.io/catalog
        imagePullPolicy: IfNotPresent
        env:
          - name: CONNECTIONSTRINGS__DEFAULTDATABASE
            valueFrom:
              secretKeyRef:
                name: recommend-coffee-secrets
                key: catalogConnectionString
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80