apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    app: ratings
    service: ratings
    version: v1
spec:
  type: ClusterIP
  selector:
    app: ratings
    service: ratings
    version: v1
  ports:
  - port: 80
    name: http
