apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels:
    app: catalog
    service: catalog
    version: v1
spec:
  type: ClusterIP
  selector:
    app: catalog
    service: catalog
    version: v1
  ports:
  - port: 80
    name: http
