apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  labels:
    app: portal
    service: portal
    version: v1
spec:
  selector:
    matchLabels:
      app: portal
      service: portal
      version: v1
  template:
    metadata:
      labels:
        app: portal
        service: portal
        version: v1
    spec:
      serviceAccountName: portal
      containers:
        - name: portal
          image: "{{ .Values.global.containerRegistry }}/portal:{{ .Values.global.releaseVersion }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: IMAGE_TAG
              value: "{{ .Chart.Version }}"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
