apiVersion: v1
kind: Service
metadata:
  name: registration
  labels:
    app: registration
    service: registration
    version: v1
spec:
  selector:
    app: registration
    service: registration
    version: v1
  ports:
  - port: 80
    name: http
