apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriptions
  labels:
    app: subscriptions
    version: {{ .Chart.Version }}
spec:
  selector:
    matchLabels:
      app: subscriptions
      version: {{ .Chart.Version }}
  template:
    metadata:
      labels:
        app: subscriptions
        version: {{ .Chart.Version }}
      annotations:
        dapr.io/app-id: "subscriptions"
        dapr.io/app-port: "80"
        dapr.io/enabled: "true"
        sidecar.opentelemetry.io/inject: "true"
        prometheus.io/port: "80"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: subscriptions
      containers:
        - name: subscriptions
          image: recommendcoffee.azurecr.io/subscriptions:{{ .Values.global.releaseVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: CONNECTIONSTRINGS__DEFAULTDATABASE
              valueFrom:
                secretKeyRef:
                  key: subscriptionsConnectionString
                  name: recommend-coffee-secrets
            - name: TELEMETRY__ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: subscriptions-config
                  key: "telemetry.endpoint"
            - name: TELEMETRY__NAME
              valueFrom:
                configMapKeyRef:
                  name: subscriptions-config
                  key: "telemetry.name"
            - name: TELEMETRY__VERSION
              valueFrom:
                configMapKeyRef:
                  name: subscriptions-config
                  key: "telemetry.version"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
      initContainers:
        - name: database-migrations
          image: recommendcoffee.azurecr.io/subscriptions-migrations:{{ .Values.global.releaseVersion }}
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: recommend-coffee-secrets
                  key: databasePassword
            - name: DB_USER
              value: sa
            - name: DB_NAME
              value: subscriptions
            - name: DB_SERVER
              value: database
