apiVersion: v1
kind: Service
metadata:
  name: subscriptions
  labels:
    app: subscriptions
    version: {{ .Chart.Version }}
spec:
  type: ClusterIP
  selector:
    app: subscriptions
    version: {{ .Chart.Version }}
  ports:
  - port: 80
    targetPort: 80
