apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
  labels:
    app: identity
    service: identity
    version: v1
spec:
  selector:
    matchLabels:
      app: identity
      service: identity
      version: v1
  template:
    metadata:
      labels:
        app: identity
        service: identity
        version: v1
      annotations:
        dapr.io/app-id: "identity"
        dapr.io/app-port: "80"
        dapr.io/enabled: "true"
        sidecar.opentelemetry.io/inject: "true"
    spec:
      serviceAccountName: identity
      containers:
        - name: identity
          image: "{{ .Values.global.containerRegistry }}/identity:{{ .Values.global.releaseVersion }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: CONNECTIONSTRINGS__DEFAULTDATABASE
              valueFrom:
                secretKeyRef:
                  name: recommend-coffee-secrets
                  key: identityConnectionString
            - name: TELEMETRY__LOGGINGENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: customermanagement-config
                  key: "telemetry.loggingEndpoint"
            - name: TELEMETRY__TRACINGENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: customermanagement-config
                  key: "telemetry.tracingEndpoint"
            - name: TELEMETRY__NAME
              valueFrom:
                configMapKeyRef:
                  name: identity-config
                  key: "telemetry.name"
            - name: TELEMETRY__VERSION
              valueFrom:
                configMapKeyRef:
                  name: identity-config
                  key: "telemetry.version"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
      initContainers:
        - name: database-migrations
          image: "{{ .Values.global.containerRegistry }}/identity-migrations:{{ .Values.global.releaseVersion }}"
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: recommend-coffee-secrets
                  key: databasePassword
            - name: DB_USER
              value: sa
            - name: DB_NAME
              value: identity
            - name: DB_SERVER
              value: database
