apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq
spec:
  selector:
    matchLabels:
      app: seq
  template:
    metadata:
      labels:
        app: seq
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: seq
        image: datalust/seq:2022.1
        ports:
        - containerPort: 5341
          name: seq
        - containerPort: 80
          name: http
        env:
        - name: ACCEPT_EULA
          value: "Y"