apiVersion: v1
kind: Service
metadata:
  name: seq
  labels:
    app: seq
    service: seq
spec:
  selector:
    app: seq
    service: seq
  ports:
  - port: 80
    targetPort: 80
    name: http-management
  - port: 5341
    targetPort: 5341
    name: http-seq
