apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  labels:
    app: ratings
    version: {{ .Chart.Version }}
spec:
  selector:
    matchLabels:
      app: ratings
      version: {{ .Chart.Version }}
  template:
    metadata:
      labels:
        app: ratings
        version: {{ .Chart.Version }}
      annotations:
        dapr.io/app-id: "ratings"
        dapr.io/app-port: "80"
        dapr.io/enabled: "true"
        sidecar.opentelemetry.io/inject: "true"
        prometheus.io/port: "80"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: ratings
      containers:
        - name: ratings
          image: "{{ .Values.global.containerRegistry }}/ratings:{{ .Values.global.releaseVersion }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: CONNECTIONSTRINGS__DEFAULTDATABASE
              valueFrom:
                secretKeyRef:
                  name: recommend-coffee-secrets
                  key: ratingsConnectionString
            - name: TELEMETRY__ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: ratings-config
                  key: "telemetry.endpoint"
            - name: TELEMETRY__NAME
              valueFrom:
                configMapKeyRef:
                  name: ratings-config
                  key: "telemetry.name"
            - name: TELEMETRY__VERSION
              valueFrom:
                configMapKeyRef:
                  name: ratings-config
                  key: "telemetry.version"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
      initContainers:
        - name: database-migrations
          image: "{{ .Values.global.containerRegistry }}/ratings-migrations:{{ .Values.global.releaseVersion }}"
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: recommend-coffee-secrets
                  key: databasePassword
            - name: DB_USER
              value: sa
            - name: DB_NAME
              value: ratings
            - name: DB_SERVER
              value: database
