apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq
  labels:
    app: seq
    service: seq
    version: v1
spec:
  selector:
    matchLabels:
      app: seq
      service: seq
      version: v1
  template:
    metadata:
      labels:
        app: seq
        service: seq
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: seq
      containers:
      - name: seq
        image: datalust/seq:2022.1
        ports:
        - containerPort: 5341
          name: http-seq
        - containerPort: 80
          name: http-management
        env:
        - name: ACCEPT_EULA
          value: "Y"