apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: recommendcoffee.azurecr.io/payments
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: CONNECTIONSTRINGS__DEFAULTDATABASE
            valueFrom:
              secretKeyRef:
                key: paymentsConnectionString
                name: recommend-coffee-secrets