apiVersion: v1
kind: Service
metadata:
  name: subscriptions
  labels:
    app: subscriptions
    service: subscriptions
    version: v1
spec:
  type: ClusterIP
  selector:
    app: subscriptions
    service: subscriptions
    version: v1
  ports:
  - port: 80
    name: http
