apiVersion: v1
kind: Service
metadata:
  name: identity
  labels:
    app: identity
    service: identity
    version: v1
spec:
  type: ClusterIP
  selector:
    app: identity
    service: identity
    version: v1
  ports:
  - port: 80
    name: http
