apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.azure.blobstorage
  version: v1
  metadata:
  - name: accountName
    secretKeyRef:
      key: recommend-coffee-secrets
      name: statestore-account-name
  - name: accountKey
    secretKeyRef:
      key: recommend-coffee-secrets
      name: statestore-account-key
  - name: containerName
    value: statemanagement
