apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: app-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https-app
      protocol: HTTPS
    hosts:
    - "recommend.coffee"
    tls:
      mode: SIMPLE
      credentialName: app-tls-secret
  - port:
      number: 443
      name: https-identity
      protocol: HTTPS
    hosts:
    - "identity.recommend.coffee"
    tls:
      mode: SIMPLE
      credentialName: identity-tls-secret