apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: smtp
  namespace: default
spec:
  type: bindings.smtp
  version: v1
  metadata:
  - name: host
    value: "emailserver"
  - name: port
    value: "25"
  - name: skipTLSVerify
    value: true
