apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: identity-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "identity.recommend.coffee"
    tls:
      mode: SIMPLE
      credentialName: recommend-coffee-tls-secret