apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: identity
spec:
  hosts:
    - "identity.recommend.coffee"
  gateways:
    - app-gateway
  http:
    - route:
      - destination:
          host: identity
          port:
            number: 80
