apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: mcr.microsoft.com/mssql/server:2019-latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 1433
        env:
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                key: databasePassword
                name: recommend-coffee-secrets
          - name: ACCEPT_EULA
            value: "Y"