apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
    name: customermanagement
spec:
    host: customermanagement
    subsets:
      - name: v1
        labels:
          version: v1
