apiVersion: v1
kind: Service
metadata:
  name: customermanagement
  labels:
    app: customermanagement
    service: customermanagement
    version: v1
spec:
  type: ClusterIP
  selector:
    app: customermanagement
    service: customermanagement
    version: v1
  ports:
  - port: 80
    name: http
