apiVersion: v1
kind: Service
metadata:
  name: timer
  labels:
    app: timer
    service: timer
    version: v1
spec:
  type: ClusterIP
  selector:
    app: timer
    service: timer
    version: v1
  ports:
  - port: 80
    name: http
