apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
    name: prometheus
    namespace: default
spec:
    selector:
        matchLabels:
            app: prometheus
    mtls:
        mode: DISABLE
