apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
    name: prometheus
spec:
    hosts:
    - prometheus
    ports:
    - number: 9090
      name: prometheus
      protocol: TCP
    - number: 8889
      name: metrics
      protocol: TCP
    resolution: DNS
    location: MESH_EXTERNAL