apiVersion: v1
kind: Service
metadata:
  name: transport
  labels:
    app: transport
    service: transport
spec:
  type: ClusterIP
  selector:
    app: transport
    service: transport
  ports:
  - port: 80
    name: http
