apiVersion: v1
kind: Secret
metadata:
  name: identity-tls-secret
  namespace: istio-system
type: kubernetes.io/tls
data:
  tls.crt: |
    {{ .Files.Get "identity-recommend-coffee.cert" | b64enc }}
  tls.key: |
    {{ .Files.Get "identity-recommend-coffee.key" | b64enc }}