apiVersion: v1
kind: Secret
metadata:
  name: recommend-coffee-secrets
type: Opaque
data:
  databasePassword: {{ .Values.databasePassword | b64enc }}
  catalogConnectionString: {{ printf "data source=database;initial catalog=catalog; user id=sa;password=%s" .Values.databasePassword | b64enc }}
  customermanagementConnectionString: {{ printf "data source=database;initial catalog=customermanagement; user id=sa;password=%s" .Values.databasePassword | b64enc }}
  paymentsConnectionString: {{ printf "data source=database;initial catalog=payments; user id=sa;password=%s" .Values.databasePassword | b64enc }}
  ratingsConnectionString: {{ printf "data source=database;initial catalog=ratings; user id=sa;password=%s" .Values.databasePassword | b64enc }}
  subscriptionsConnectionString: {{ printf "data source=database;initial catalog=subscriptions;user id=sa;password=%s" .Values.databasePassword | b64enc }}
  identityConnectionString: {{ printf "data source=database;initial catalog=identity;user id=sa;password=%s" .Values.databasePassword | b64enc }}
  shippingConnectionString: {{ printf "data source=database;initial catalog=shipping;user id=sa;password=%s" .Values.databasePassword | b64enc }}
  recommendationsConnectionString: {{ printf "data source=database;initial catalog=recommendations;user id=sa;password=%s" .Values.databasePassword | b64enc }}