apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: identity-virtual-service
spec:
  hosts:
  - "recommend.coffee"
  gateways:
  - recommendcoffee-gateway
  http:
  - name: identity-route
    match:
      - uri:
          prefix: /identity/
    rewrite:
      uri: /
    route:
    - destination:
        host: identity
        port:
          number: 80