apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
    name: zipkin
    namespace: default
spec:
    selector:
        matchLabels:
            app: zipkin
    mtls:
        mode: DISABLE
