apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
    name: zipkin
spec:
    hosts:
    - zipkin
    ports:
    - number: 9411
      name: http
      protocol: HTTP
    resolution: DNS
    location: MESH_EXTERNAL