apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: zipkin-virtual-service
spec:
  hosts:
  - "stats.recommend.coffee"
  gateways:
  - recommendcoffee-stats-gateway
  http:
  - name: zipkin-route
    match:
      - uri:
          prefix: /zipkin/
    route:
    - destination:
        host: zipkin
        port:
          number: 9411