apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  labels:
    app: portal
    version: {{ .Chart.Version }}
spec:
  selector:
    matchLabels:
      app: portal
      version: {{ .Chart.Version }}
  template:
    metadata:
      labels:
        app: portal
        version: {{ .Chart.Version }}
    spec:
      serviceAccountName: portal
      containers:
        - name: portal
          image: recommendcoffee.azurecr.io/portal:{{ .Values.global.releaseVersion }}
          imagePullPolicy: IfNotPresent
          env:
            - name: IMAGE_TAG
              value: "{{ .Chart.Version }}"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
