apiVersion: v1
kind: Service
metadata:
  name: portal
  labels:
    app: portal
    service: portal
    version: v1
spec:
  type: ClusterIP
  selector:
    app: portal
    service: portal
    version: v1
  ports:
  - port: 80
    name: http
