apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: portal-virtual-service
spec:
  hosts:
  - "recommend.coffee"
  gateways:
  - recommendcoffee-gateway
  http:
  - name: portal-route
    match:
      - uri:
          prefix: /
    route:
    - destination:
        host: portal
        port:
          number: 80