name: Build and push images

on:
  push:
    branches: [ main ]

env:
  BUILD_ID: "${{ github.sha }}"

jobs:
  build:
    name: 'Build and push artifacts'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: 'Checkout sources'
    - run: |
        ./build-images.ps1 -ReleaseVersion $BUILD_ID
      shell: pwsh
      name: 'Build docker images'
    - name: 'Login to container registry'
      uses: azure/docker-login@v1
      with:
        login-server: tastybeans.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        helm registry login tastybeans.azurecr.io --username ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_PASSWORD }}
      name: 'Login to helm registry'
    - run: |
        ./push-images.ps1 -ReleaseVersion $BUILD_ID
      shell: pwsh
      name: 'Push docker images to remote registry'
    - run: |
        helm push ./charts/tasty-beans oci://tastybeans.azurecr.io/helm
      name: 'Push helm chart to remote registry'